network:
  version: 2
  ethernets:
    eth1:
      dhcp4: true
      optional: true
    eth2:
      addresses:
        - 10.10.10.2/24
      gateway4: 10.10.10.1
      nameservers:
        addresses:
          - 10.10.10.1
          - 1.1.1.1
      optional: false
